apiVersion: v1
kind: PersistentVolume
metadata:
  name: gambly-electric-dev-pv
  labels:
    app: gambly-electric
    env: dev
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b37043cf4d3bd4bc::fsap-074e9b709e11f0aa0
