apiVersion: v1
kind: PersistentVolume
metadata:
  name: gambly-electric-prod-pv
  labels:
    app: gambly-electric
    env: prod
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0ade713452d6b7f7b::fsap-0407f2e3b4e5698e6
