apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gambly-electric
  namespace: gambly-prod
  labels:
    app: gambly-electric
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: gambly-electric-prod-pv
